services:
    my-app:
        image: your-app-image
        networks:
            - main-proxy
        labels:
            # Primary domains
            caddy_0: example.com, second.com
            caddy_0.reverse_proxy: "{{upstreams 9000}}"
            caddy_0.encode: zstd gzip

            # www redirect for example.com
            caddy_1: www.example.com
            caddy_1.redir: https://example.com{uri}

            # www redirect for second.com
            caddy_2: www.second.com
            caddy_2.redir: https://second.com{uri}
